DETECTION_PROMPT = """You are reviewing two shots from a video project. These may be from a traditional film shoot or from AI-generated clips (Runway, Veo, Kling, Sora, Pika, or others).

You will see multiple frames per shot (typically 3 frames sampled at 25% / 50% / 75% of each shot's duration). Frames labelled "SHOT A" are the earlier shot — the reference. Frames labelled "SHOT B" are the shot under review.

Use multi-frame coverage to your advantage: an object or anomaly that appears in only SOME frames is a stronger signal than one visible in all frames.

---

There are four kinds of errors to look for:

1. STANDALONE ERRORS in Shot B — things wrong regardless of Shot A:
   - An anachronistic prop (e.g. a modern object in a historical setting)
   - Visible production equipment or crew in frame
   - Wardrobe that doesn't match the scene's established world

2. CROSS-SHOT CONTINUITY ERRORS — only if A and B show the same physical location/character from a different angle AND you can confirm it is the same scene moment:
   - A prop that was in one position in A and is noticeably different in B
   - A wardrobe item (button, collar, sleeve) that visibly changed between A and B
   - Hair or makeup that changed significantly between A and B

3. TEMPORAL/CAUSATION ERRORS — effects appearing before their causes:
   - Bullet holes, damage, blood, or broken glass visible in one shot, but the event causing them is shown in the other shot
   - A character holding an object in Shot A that wasn't picked up yet

4. AI CLIP CONSISTENCY ERRORS — flag when the two shots don't match in ways that make the cut feel broken. These are especially common when clips were generated by different AI models or at different times:
   - LIGHTING MISMATCH (type: "lighting"): Significantly different color temperature, overall exposure, or color grade between shots. E.g. Shot A is warm golden-hour and Shot B is cool overcast; one is high-contrast and the other is washed out. Flag these even if the shots have different camera angles — for video projects, consistent lighting across cuts is always a concern.
   - ATMOSPHERE MISMATCH (type: "atmosphere"): Different weather, time of day, season, or background environment. E.g. clear sunny sky vs storm clouds; summer greenery vs bare winter trees; noon light vs blue-hour dusk; desert landscape vs rocky shoreline — any case where the overall backdrop or environment of the scene changes dramatically across frames.
   - STYLE MISMATCH (type: "other"): The shots appear to come from visually incompatible styles — e.g. one is realistic and cinematic while the other looks clearly synthetic or over-processed; one has heavy film grain while the other is perfectly clean.

   For AI clip consistency errors:
   - object_query: phrase targeting the affected aspect — "lighting and color grade", "sky and atmosphere", "overall color temperature", "visual style"
   - fix_suggestion: a direct comparative instruction — e.g. "Regrade Shot B to match the warm golden-hour tone of Shot A" or "Change the sky in Shot B to match the clear conditions in Shot A"
   - fix_target_shot: "B" (Shot A is the reference; Shot B gets fixed)

---

Rules:
- DO NOT flag subtle lighting shifts clearly caused by camera angle (shadows from a different direction, natural exposure shift when pointing toward a window). DO flag significant mood or grade differences that would be noticeable on a cut.
- DO NOT flag both "atmosphere" and "lighting" for the same root cause. If a lighting mismatch is a direct consequence of an environment/atmosphere change (e.g. desert sunset → overcast shoreline makes everything warmer→cooler), flag it as "atmosphere" only. Only flag "lighting" independently if the environment is the same but the color grade or exposure differs.
- DO NOT flag action progression (characters moved naturally), extras repositioning, or intentional scene transitions.
- If A and B are clearly MEANT to be different scenes (an intentional narrative cut: flashback, time jump, cutaway to a different day or storyline), return {"errors": [], "different_scene": true}. IMPORTANT: for AI-generated footage, dramatically different backgrounds (desert vs. rocky shoreline, different weather, different time of day) within the same sequence are usually generation inconsistencies, NOT intentional cuts. If the shots share a subject (e.g. same character/astronaut), flag the background mismatch as an "atmosphere" error rather than returning different_scene: true.
- Without a user hint: 1–3 high-confidence errors is better than 8 uncertain ones.
- With a user hint at the top: trust it and flag what they described.

For each error return:
- type: one of [prop, wardrobe, lighting, hair, set_dressing, eyeline, atmosphere, other]
  * set_dressing = specific identifiable object/prop on the set changed (a vase moved, a lamp appeared). NOT for whole-background or environment changes — those are "atmosphere".
  * atmosphere = any whole-scene environment difference: weather, time of day, season, or a dramatically different backdrop/location.
- description: one sentence — what the problem is and which shot has it.
- fix_suggestion: ONE clean imperative sentence. No alternatives, no production notes.
- severity: low | medium | high
- object_query: SHORT noun phrase 2–5 words naming the target (e.g. "modern coffee cup", "lighting and color grade", "sky and atmosphere"). Required — fed to downstream localization.
- fix_target_shot: "A" or "B" — which shot needs fixing.
  * Standalone or cross-shot error in Shot B → "B"
  * Shot A is the wrong one (temporal error, etc.) → "A"
  * AI clip consistency error → "B" (A is the reference)

Do NOT output bounding boxes — a separate model handles localization.

Return STRICT JSON only:
{
  "different_scene": false,
  "errors": [
    { "type": "...", "description": "...", "fix_suggestion": "...", "severity": "...", "object_query": "...", "fix_target_shot": "A" or "B" }
  ]
}

If no errors: {"different_scene": false, "errors": []}"""


STANDALONE_PROMPT = """You are reviewing keyframes from a SINGLE SHOT of a film for things that don't belong in the scene's world.

Look at the frames carefully. Identify any STANDALONE errors visible in this shot:
- Anachronistic props (modern objects in historical settings — coffee cups, plastic bottles, smartphones, wristwatches, etc.)
- Visible production equipment (microphones, cameras, crew, light stands, reflections of crew)
- Wardrobe items that don't match the scene's established world
- Background/environment inconsistency WITHIN the shot: if the background changes dramatically across frames (e.g. frame 1 shows a desert at sunset, frame 3 shows a rocky shoreline — a dramatic environment shift within what should be a continuous shot), flag this as type "atmosphere"
- Anything else that clearly does NOT belong in the scene

For each error return:
- type: one of [prop, wardrobe, lighting, hair, set_dressing, eyeline, atmosphere, other]
  * set_dressing = a specific identifiable prop or object on the set that doesn't belong (a vase, a lamp, a piece of furniture). NOT for whole-background or environment changes.
  * atmosphere = the overall backdrop or environment changes dramatically across frames (e.g. desert to rocky shoreline, sunny sky to storm clouds, different time of day). Use this when the whole scene background shifts, not a specific object.
  * lighting = the overall color temperature, exposure, or grade changes significantly across frames.
- description: one sentence describing the error
- fix_suggestion: ONE clean imperative sentence (e.g. "Remove the coffee cup from the table"). For atmosphere/lighting errors, describe the whole-scene correction (e.g. "Match the background environment across all frames to the warm sunset desert").
- object_query: SHORT noun phrase 2–5 words naming the target. For atmosphere errors use "background environment" or "sky and landscape"; for lighting use "lighting and color grade".
- severity: low | medium | high

CRITICAL: you must VISUALLY CONFIRM the error in the frames before flagging. If you cannot see it in any frame, do not flag. Honest "I don't see it" beats confident hallucination.

Return STRICT JSON only:
{
  "errors": [
    { "type": "...", "description": "...", "fix_suggestion": "...", "object_query": "...", "severity": "..." }
  ]
}

If no errors: {"errors": []}"""


def build_standalone_prompt(user_hint: str = "") -> str:
    hint = (user_hint or "").strip()
    if not hint:
        return STANDALONE_PROMPT
    return (
        "USER HINT — the person who uploaded this footage said:\n"
        f'  "{hint}"\n\n'
        "How to use this hint:\n"
        "1. The hint tells you WHERE to look and WHAT KIND of error to search for.\n"
        "2. You must VISUALLY CONFIRM the error in the frames before flagging. The hint is a guide, NOT a guarantee.\n"
        "3. If the hint describes an error but the frames don't show it, return no errors. Honest 'I don't see it' beats hallucination.\n\n"
        + STANDALONE_PROMPT
    )


def build_detection_prompt(user_hint: str = "") -> str:
    """Detection prompt, optionally prefixed with the user's own intent."""
    hint = (user_hint or "").strip()
    if not hint:
        return DETECTION_PROMPT
    return (
        "USER HINT — the person who uploaded this footage said:\n"
        f'  "{hint}"\n\n'
        "How to use this hint:\n"
        "1. The hint tells you WHERE to look and WHAT KIND of error to search "
        "for. Search the frames methodically with that in mind.\n"
        "2. CRITICAL: you must VISUALLY CONFIRM the error in the actual frames "
        "before flagging. The hint is a guide, NOT a guarantee. Do not invent "
        "errors that match the hint's description if you cannot see them.\n"
        "3. The bbox you return must precisely point at the visual evidence in "
        "the frame. If you cannot pinpoint it, do NOT flag it.\n"
        "4. If the hint describes an error but neither frame visually shows it, "
        "return no errors for this pair. The error may exist elsewhere in the "
        "clip — that's fine, other pairs may catch it.\n"
        "5. Honest 'I don't see it' is much better than confident hallucination. "
        "A false-positive is worse than a missed detection.\n\n"
        + DETECTION_PROMPT
    )


HOLISTIC_PROMPT = """You are reviewing a sequence of clips from an AI video project. These clips should feel like one cohesive scene, but they may have been generated at different times or by different AI models.

Look at ALL shots together and identify any that stand out as inconsistent with the overall sequence — specifically:
- LIGHTING / COLOR GRADE (type: "lighting"): One clip has a noticeably warmer/cooler, brighter/darker, or differently graded tone than the majority
- ATMOSPHERE (type: "atmosphere"): One clip shows different weather, time of day, season, or environmental conditions than the others
- STYLE MISMATCH (type: "other"): One clip looks like it came from a different AI model or style — different sharpness, grain, rendering quality, or overall aesthetic

Rules:
- Compare each shot against the OVERALL PATTERN of the full sequence, not just its neighbors
- Only flag clips with clear, significant differences that would be noticeable on a cut
- Minor lighting angle shifts or color variation are expected — flag only jarring mismatches
- If the sequence is consistent, return {"outliers": []}
- Reference shots by the number in their label (Shot 1 → shot_index 0, Shot 2 → shot_index 1, etc.)

For each outlier return:
- shot_index: 0-based index of the outlier shot
- type: "lighting" | "atmosphere" | "other"
- description: one sentence — what is different about this clip vs. the others
- fix_suggestion: one imperative instruction (e.g. "Regrade this clip to match the warm golden-hour tone of the surrounding shots" or "Change the sky to overcast to match the rest of the sequence")
- severity: "low" | "medium" | "high"

Return STRICT JSON only:
{"outliers": [{"shot_index": 0, "type": "...", "description": "...", "fix_suggestion": "...", "severity": "..."}]}

If all consistent: {"outliers": []}"""


def build_holistic_prompt(user_hint: str = "") -> str:
    hint = (user_hint or "").strip()
    if not hint:
        return HOLISTIC_PROMPT
    return (
        "USER HINT — the person who uploaded this footage said:\n"
        f'  "{hint}"\n\n'
        "Use this hint to focus your review on the specific consistency issue they described.\n\n"
        + HOLISTIC_PROMPT
    )


_ADD_VERBS = ("add", "place", "put", "insert", "restore", "bring back", "return", "reintroduce")
_REMOVE_VERBS = ("remove", "erase", "delete", "hide")
_TRANSFORM_VERBS = (
    "regrade", "change", "adjust", "shift", "match", "apply",
    "convert", "alter", "transform", "make", "update", "fix",
    "correct", "modify", "replace the lighting", "replace the atmosphere",
)
_ALT_CUTS = (
    " or replace",
    " or substitute",
    " or swap",
    " in post-production",
    " in post production",
    "; replace",
)


def _strip_alternatives(s: str) -> str:
    """Trim 'or replace with X' / 'in post-production' tails so we keep a clean imperative."""
    s = s.strip().rstrip(".")
    low = s.lower()
    for cut in _ALT_CUTS:
        idx = low.find(cut)
        if idx > 0:
            s = s[:idx]
            low = s.lower()
    return s.rstrip(" ,")


def _starts_with_remove_verb(s: str) -> bool:
    low = s.lower()
    return any(low.startswith(v + " ") for v in _REMOVE_VERBS)


def _starts_with_add_verb(s: str) -> bool:
    low = s.lower()
    return any(low.startswith(v + " ") for v in _ADD_VERBS)


def _is_transform_instruction(s: str) -> bool:
    """Returns True when the string is a whole-clip transformation instruction
    (e.g. 'Regrade this clip to match...') rather than a replacement description
    (e.g. 'a wooden goblet' or 'empty table surface')."""
    low = s.lower().lstrip()
    return any(low.startswith(v + " ") or low.startswith(v + " the ") for v in _TRANSFORM_VERBS)


def _extract_object(imperative: str) -> str:
    """From 'Remove the coffee cup from the table' → 'the coffee cup'."""
    s = imperative.strip().rstrip(".")
    for verb in _REMOVE_VERBS:
        if s.lower().startswith(verb + " "):
            s = s[len(verb):].strip()
            break
    for cut in (" from the ", " from ", " on the ", " on ",
                " in the ", " in ", " at the ", " at "):
        idx = s.lower().find(cut)
        if idx > 0:
            s = s[:idx]
            break
    return s.strip() or "the unwanted object"


def build_aleph_prompt(
    error: dict,
    has_marker: bool = False,
    in_video_marker: bool = False,
) -> str:
    """
    Build a short, direct Aleph imperative.

    - in_video_marker=True: a red rectangle is burned into every frame of
      the input clip. Strongest spatial signal. The prompt tells Aleph to
      remove what's inside that on-screen rectangle along with the rectangle
      itself.
    - has_marker=True (legacy): a separate reference image is provided via
      Aleph's `references` array. Weaker than in-video — Aleph may ignore it.
    - Both False: text-only prompt.
    - Whole-clip transforms (lighting, atmosphere, style): when replaceWith is
      a transformation instruction, use it directly — no marker needed.
    """
    fix_mode = (error.get("fixMode") or "remove").lower()

    # Whole-clip transformation: lighting/atmosphere/style fix where replaceWith
    # is already a full imperative instruction (e.g. "Regrade this clip to match
    # the warm golden-hour tone of the surrounding shots"). Use it directly.
    if fix_mode == "replace":
        replace_with = (error.get("replaceWith") or "").strip().rstrip(".")
        if replace_with and _is_transform_instruction(replace_with):
            base = replace_with.rstrip(".")
            ref_clause = (
                " Use the reference image as the visual target for the correct look."
                if has_marker else ""
            )
            return (
                base + "." + ref_clause + " "
                "Apply this change uniformly to every frame of the clip "
                "from the very first frame to the very last — do not fade, "
                "revert, or apply it to only part of the clip duration."
            )

    if in_video_marker:
        replace_with = (error.get("replaceWith") or "").strip().rstrip(".")
        err_type = (error.get("type") or "").lower()
        is_wardrobe_type = err_type in ("wardrobe", "hair")

        is_set_dressing_type = err_type in ("set_dressing", "prop")

        if fix_mode == "replace" and replace_with:
            if is_wardrobe_type:
                # Wardrobe/hair: restore the original item without affecting anything
                # else. The fixSuggestion is already a clean imperative so use it
                # directly, then constrain Aleph to only touch the red-boxed region.
                return (
                    f"In this video there is a red rectangle drawn on the screen "
                    f"marking a wardrobe inconsistency to correct. "
                    f"{replace_with}. "
                    f"Only change the clothing or hair item inside the red rectangle — "
                    f"do not alter the actor's face, pose, skin, or any other part of "
                    f"the scene. Remove the red rectangle. The result must look "
                    f"natural and seamless, as if the item was always correct."
                )
            if is_set_dressing_type and _starts_with_add_verb(replace_with):
                # Object is missing from this shot and needs to be added — the red
                # rectangle marks WHERE it should appear, not something to replace.
                return (
                    f"In this video there is a red rectangle drawn on the screen "
                    f"marking a location where an object is missing. "
                    f"{replace_with}. "
                    f"Place the object naturally inside the red rectangle area, "
                    f"matching the scene's existing lighting, shadows, and perspective. "
                    f"Remove the red rectangle. The result must look as if the object "
                    f"was always there."
                )
            return (
                f"In this video there is a red rectangle drawn on the screen. "
                f"Replace the object inside the red rectangle with {replace_with}. "
                f"Remove the red rectangle entirely. The final video must show "
                f"no rectangle and no original object — only {replace_with} in "
                f"that location, blending naturally with the surroundings."
            )
        return (
            "In this video there is a red rectangle drawn on the screen. "
            "Remove BOTH the red rectangle AND the object inside it. "
            "Fill the entire rectangle region with the surrounding background "
            "(table surface, wall, whatever is naturally behind it). The final "
            "video must show no rectangle and no object inside it — completely "
            "clean as if neither was ever there."
        )

    fix_mode = (error.get("fixMode") or "remove").lower()
    raw_fix = (error.get("fixSuggestion") or "").strip()
    fix = _strip_alternatives(raw_fix)
    description = (error.get("description") or "").strip().rstrip(".")

    obj_phrase = (
        _extract_object(fix)
        if _starts_with_remove_verb(fix)
        else (description or "the unwanted object")
    )

    if fix_mode == "replace":
        replace_with = (error.get("replaceWith") or "").strip().rstrip(".")
        if not replace_with:
            # User toggled replace but didn't say what — safer to remove
            # rather than let Aleph improvise.
            return _build_remove_prompt(fix, obj_phrase, has_marker)
        if has_marker:
            return (
                f"Replace the object outlined in red in the @marker reference "
                f"with {replace_with}. The replacement should match the scene's "
                f"lighting and surroundings."
            )
        return f"Replace {obj_phrase} with {replace_with}."

    return _build_remove_prompt(fix, obj_phrase, has_marker)


def _build_remove_prompt(fix: str, obj_phrase: str, has_marker: bool) -> str:
    if has_marker:
        return (
            f"Remove the object outlined in red in the @marker reference. "
            f"Fill the empty space with the surrounding table surface and "
            f"background. {obj_phrase.capitalize()} should not be visible in "
            f"any frame."
        )
    if _starts_with_remove_verb(fix):
        return f"{fix}. Fill the empty space with the surrounding background."
    if fix:
        return f"Remove {fix}. Fill the empty space with the surrounding background."
    return (
        f"Remove {obj_phrase}. Fill the empty space with the surrounding background."
    )


def compute_continuity_score(errors: list) -> int:
    high_count = sum(1 for e in errors if e.get("severity") == "high")
    score = max(0, 100 - (len(errors) * 8) - (high_count * 5))
    return score
